#!/usr/bin/env python3
"""Verify the Granite governed-project example after local edits.

This is the example's self-contained local verifier gate. It runs from the
example root, confirms the governed document spine is present, checks that the
README/AGENTS/AI_FLOW surfaces keep their governance and gate vocabulary, then
delegates to the bundled tools for the docs index check, the drift self-test
and check, and the static safety scan. A green run is reproducible evidence:
anyone can re-run it and observe the same pass or fail result.

The example is a worked governed-adoption example, not a product with a test
suite. R0 is a documentation authority baseline, so this verifier governs the
documentation evidence chain; behavior tests and scenario fixtures become
required once product implementation starts (see
``docs/evaluation/scenario-regression.md``).
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# The example's actual governed spine. This list mirrors the files that really
# ship in examples/governed-project, not the template's slightly different set.
REQUIRED_FILES = [
    "README.md",
    "README.zh-CN.md",
    "GOAL.md",
    "LESSONS.md",
    "AGENTS.md",
    "ai-collaborative-development-standards.md",
    ".github/PULL_REQUEST_TEMPLATE.md",
    "docs/AI_FLOW.md",
    "docs/INDEX.md",
    "docs/product/prd.md",
    "docs/design/architecture.md",
    "docs/design/technical-solution.md",
    "docs/roadmap/README.md",
    "docs/roadmap/features.md",
    "docs/roadmap/current-status.md",
    "docs/plans/README.md",
    "docs/dev_log/2026-06-05-governance-spine-adoption.md",
    "docs/lessons/2026-06-05-docs-index-boundary.md",
    "docs/lessons/_drift_report.md",
    "docs/practices/README.md",
    "docs/practices/2026-06-05-governed-project-knowledge-spine.md",
    "docs/evaluation/scenario-regression.md",
    "docs/release/release-governance.md",
    "scripts/verify_project.py",
    "tools/build_docs_index.py",
    "tools/docs_drift_signal.py",
    "tools/static_safety_scan.py",
]

TEXT_SUFFIXES = {"", ".md", ".py", ".yml", ".yaml", ".toml", ".gitignore"}
SKIP_PARTS = {".git", ".codegraph", "__pycache__", ".pytest_cache", ".venv"}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"verification failed: {message}")


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def iter_text_files() -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        if any(part in SKIP_PARTS for part in path.parts):
            continue
        if path.is_file() and (path.name == ".gitignore" or path.suffix.lower() in TEXT_SUFFIXES):
            files.append(path)
    return sorted(files)


def run_command(args: list[str], failure_message: str) -> None:
    result = subprocess.run(args, cwd=ROOT, text=True, capture_output=True)
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    require(result.returncode == 0, failure_message)


def check_files() -> None:
    missing = [rel for rel in REQUIRED_FILES if not (ROOT / rel).exists()]
    require(not missing, "missing required files: " + ", ".join(missing))


def check_markers() -> None:
    # Both READMEs must demonstrate the local verifier, static safety, index,
    # drift, scenario-regression, and release-governance gate vocabulary so the
    # worked example stays in sync with the P2 gate set.
    readme_markers = (
        "scripts/verify_project.py",
        "tools/static_safety_scan.py",
        "tools/build_docs_index.py",
        "tools/docs_drift_signal.py",
        "docs/evaluation/scenario-regression.md",
        "docs/release/release-governance.md",
        "docs/lessons/_drift_report.md",
    )
    for rel in ("README.md", "README.zh-CN.md"):
        content = read(rel)
        for marker in readme_markers:
            require(marker in content, f"{rel} missing gate marker: {marker}")

    # Agents and the local flow must point at the runnable gates rather than at
    # commands that do not exist in this example.
    for rel in ("AGENTS.md", "docs/AI_FLOW.md"):
        content = read(rel)
        for marker in (
            "scripts/verify_project.py",
            "tools/static_safety_scan.py",
            "docs/evaluation/scenario-regression.md",
            "docs/release/release-governance.md",
        ):
            require(marker in content, f"{rel} missing gate marker: {marker}")

    index = read("docs/INDEX.md")
    require("AUTO-GENERATED by tools/build_docs_index.py" in index, "docs/INDEX.md must be generated")
    forbidden_root_links = (
        "(GOAL.md)", "(../GOAL.md)", "(README.md)", "(../README.md)",
        "(README.zh-CN.md)", "(../README.zh-CN.md)", "(LESSONS.md)", "(../LESSONS.md)",
    )
    require(not any(link in index for link in forbidden_root_links), "docs/INDEX.md must stay docs-directory-only")


def check_links() -> None:
    # The example is nested inside the Lithos repository and legitimately links
    # up to repo-root standard docs (../../README.md, ../../docs/...), so this
    # check confirms each relative link target exists rather than forbidding
    # links that leave the example directory.
    link_re = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
    for path in iter_text_files():
        if path.suffix.lower() != ".md":
            continue
        text = path.read_text(encoding="utf-8")
        rel = str(path.relative_to(ROOT))
        for raw_target in link_re.findall(text):
            if raw_target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            target = raw_target.split("#", 1)[0]
            if not target or target.startswith("<"):
                continue
            resolved = (path.parent / target).resolve()
            require(resolved.exists(), f"{rel}: missing link target: {raw_target}")


def main() -> int:
    check_files()
    check_markers()
    check_links()
    run_command([sys.executable, "tools/build_docs_index.py", "--check"], "docs index check failed")
    run_command([sys.executable, "tools/docs_drift_signal.py", "--self-test"], "docs drift self-test failed")
    run_command([sys.executable, "tools/docs_drift_signal.py", "--check"], "docs drift check failed")
    run_command([sys.executable, "tools/static_safety_scan.py"], "static safety scan failed")
    print(f"Granite example verification passed. Checked {len(REQUIRED_FILES)} required files and {len(iter_text_files())} text files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
